# Importing NumPy

import numpy as np

# Load File

In [5]:
import numpy as np

In [6]:
iris = np.genfromtxt('D:\Downloads\IRIS.csv',skip_header=1, delimiter=',' ,dtype=float, encoding=None)

In [7]:
iris

array([[5.1, 3.5, 1.4, 0.2, nan, 1. ],
       [4.9, 3. , 1.4, 0.2, nan, 1. ],
       [4.7, 3.2, 1.3, 0.2, nan, 1. ],
       [4.6, 3.1, 1.5, 0.2, nan, 1. ],
       [5. , 3.6, 1.4, 0.2, nan, 1. ],
       [5.4, 3.9, 1.7, 0.4, nan, 1. ],
       [4.6, 3.4, 1.4, 0.3, nan, 1. ],
       [5. , 3.4, 1.5, 0.2, nan, 1. ],
       [4.4, 2.9, 1.4, 0.2, nan, 1. ],
       [4.9, 3.1, 1.5, 0.1, nan, 1. ],
       [5.4, 3.7, 1.5, 0.2, nan, 1. ],
       [4.8, 3.4, 1.6, 0.2, nan, 1. ],
       [4.8, 3. , 1.4, 0.1, nan, 1. ],
       [4.3, 3. , 1.1, 0.1, nan, 1. ],
       [5.8, 4. , 1.2, 0.2, nan, 1. ],
       [5.7, 4.4, 1.5, 0.4, nan, 1. ],
       [5.4, 3.9, 1.3, 0.4, nan, 1. ],
       [5.1, 3.5, 1.4, 0.3, nan, 1. ],
       [5.7, 3.8, 1.7, 0.3, nan, 1. ],
       [5.1, 3.8, 1.5, 0.3, nan, 1. ],
       [5.4, 3.4, 1.7, 0.2, nan, 1. ],
       [5.1, 3.7, 1.5, 0.4, nan, 1. ],
       [4.6, 3.6, 1. , 0.2, nan, 1. ],
       [5.1, 3.3, 1.7, 0.5, nan, 1. ],
       [4.8, 3.4, 1.9, 0.2, nan, 1. ],
       [5. , 3. , 1.6, 0.

# Drop col index no.4

In [8]:
iris = iris [0:150,[0,1,2,3,5]]
iris

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

# Display the shape, dimensions and size of iris

In [9]:
iris.shape

(150, 5)

In [10]:
iris.ndim

2

In [11]:
iris.size

750

# Split iris to iris1, iris2, and iris3

In [12]:
iris1, iris2, iris3 =np.split(iris,[50,100], axis=0)

In [13]:
iris1

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [14]:
iris2

array([[7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [4.9, 2.4, 3.3, 1. , 2. ],
       [6.6, 2.9, 4.6, 1.3, 2. ],
       [5.2, 2.7, 3.9, 1.4, 2. ],
       [5. , 2. , 3.5, 1. , 2. ],
       [5.9, 3. , 4.2, 1.5, 2. ],
       [6. , 2.2, 4. , 1. , 2. ],
       [6.1, 2.9, 4.7, 1.4, 2. ],
       [5.6, 2.9, 3.6, 1.3, 2. ],
       [6.7, 3.1, 4.4, 1.4, 2. ],
       [5.6, 3. , 4.5, 1.5, 2. ],
       [5.8, 2.7, 4.1, 1. , 2. ],
       [6.2, 2.2, 4.5, 1.5, 2. ],
       [5.6, 2.5, 3.9, 1.1, 2. ],
       [5.9, 3.2, 4.8, 1.8, 2. ],
       [6.1, 2.8, 4. , 1.3, 2. ],
       [6.3, 2.5, 4.9, 1.5, 2. ],
       [6.1, 2.8, 4.7, 1.2, 2. ],
       [6.4, 2.9, 4.3, 1.3, 2. ],
       [6.6, 3. , 4.4, 1.4, 2. ],
       [6.8, 2.8, 4.8, 1.4, 2. ],
       [6.7, 3. , 5. , 1.7, 2. ],
       [6. , 2.9, 4.5, 1.5, 2. ],
       [5.7, 2

# Create header

In [15]:
header = np.array([['sepal length'],['sepal width'],['petal length'],['petal width'],['Species No']])

In [16]:
header

array([['sepal length'],
       ['sepal width'],
       ['petal length'],
       ['petal width'],
       ['Species No']], dtype='<U12')

# Iris Descriptive Statistics

In [17]:
iris_max = iris[:,0:4].max(axis=0)
iris_max

array([7.9, 4.4, 6.9, 2.5])

In [18]:
iris_min = iris[:,0:4].min(axis=0)
iris_min

array([4.3, 2. , 1. , 0.1])

In [19]:
iris_avg = iris[:,0:4].mean(axis=0).round(2)
iris_avg

array([5.84, 3.05, 3.76, 1.2 ])

In [20]:
iris_std = iris[:,0:4].std(axis=0).round(2)
iris_std

array([0.83, 0.43, 1.76, 0.76])

In [21]:
iris_var = iris[:,0:4].var(axis=0).round(2)
iris_var

array([0.68, 0.19, 3.09, 0.58])

# iris1, iris2, and iris3 Descriptive Statistics

In [23]:
iris1_max = iris2[:,0:4].max(axis=0)
iris1_max

array([7. , 3.4, 5.1, 1.8])

In [47]:
iri2_max = iris2[:,0:4].max(axis=0)
iri2_max

array([7. , 3.4, 5.1, 1.8])

In [25]:
iris3_max = iris3[:,0:4].max(axis=0)
iris3_max

array([7.9, 3.8, 6.9, 2.5])

In [26]:
iris1_min = iris1[:,0:4].min(axis=0)
iris1_min

array([4.3, 2.3, 1. , 0.1])

In [27]:
iris2_min = iris2[:,0:4].min(axis=0)
iris2_min

array([4.9, 2. , 3. , 1. ])

In [28]:
iris3_min = iris3[:,0:4].min(axis=0)
iris3_min

array([4.9, 2.2, 4.5, 1.4])

In [31]:
iris1_avg = iris1[:,0:4].mean(axis=0).round(2)
iris1_avg

array([5.01, 3.42, 1.46, 0.24])

In [33]:
iris2_avg = iris2[:,0:4].mean(axis=0).round(2)
iris2_avg

array([5.94, 2.77, 4.26, 1.33])

In [34]:
iris3_avg = iris3[:,0:4].mean(axis=0).round(2)
iris3_avg

array([6.59, 2.97, 5.55, 2.03])

In [35]:
iris1_std = iris1[:,0:4].std(axis=0).round(2)
iris1_std

array([0.35, 0.38, 0.17, 0.11])

In [36]:
iris2_std = iris2[:,0:4].std(axis=0).round(2)
iris2_std

array([0.51, 0.31, 0.47, 0.2 ])

In [37]:
iris3_std = iris3[:,0:4].std(axis=0).round(2)
iris3_std

array([0.63, 0.32, 0.55, 0.27])

In [38]:
iris1_var = iris1[:,0:4].var(axis=0).round(2)
iris1_var

array([0.12, 0.14, 0.03, 0.01])

In [39]:
iris2_var = iris2[:,0:4].var(axis=0).round(2)
iris2_var

array([0.26, 0.1 , 0.22, 0.04])

In [40]:
iris3_var = iris3[:,0:4].var(axis=0).round(2)
iris3_var

array([0.4 , 0.1 , 0.3 , 0.07])

# Compare Iris setosa’s average sepal width to that of Iris virginica.

In [42]:
iris1_avg[1] > iris3_avg[1]

True

# Compare Iris setosa’s average petal length to that of Iris virginica.

In [44]:
iris1_avg[3] > iris3_avg[3]

False

# Save into IrisStat.txt

In [53]:
np.savetxt('D:/numpy output project.txt',( iris1_max,iri2_max,iris3_max,iris1_avg,iris2_avg,iris3_avg,iris1_min,iris2_min,iris3_min,iris1_std,iris2_std,iris3_std,iris1_var,iris2_var,iris3_var),fmt='%s',delimiter=',')